config:
  send_anonymous_usage_stats: False

ecommerce_dwh:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      password: password
      dbname: ecommerce_dwh
      schema: landing